### ISSUE TITLE
Unable to install pygrib 2.0.5

### ISSUE THREAD

**Issue by fox91** [jswhit/pygrib#161]
- OS: `Amazon Linux 2`
- Python: `3.8.6`
- ecCodes:
    - `2.18.0` (built from source with cmake `3.18.4`)
    - `2.18.0` (built from source with cmake `3.19.1`)
    - `2.19.1` (built from source with cmake `3.19.1`)
- gcc `(GCC) 7.3.1 20180712 (Red Hat 7.3.1-9)`

I'm unable to install `pygrib==2.0.5`:

<details open>
  <summary>Click to see logs</summary>

```
$ pip install --upgrade pygrib==2.0.5
Collecting pygrib==2.0.5
  Using cached pygrib-2.0.5.tar.gz (21.5 MB)
Collecting numpy
  Using cached numpy-1.19.4-cp38-cp38-manylinux2010_x86_64.whl (14.5 MB)
Collecting pyproj
  Using cached pyproj-3.0.0.post1-cp38-cp38-manylinux2010_x86_64.whl (6.5 MB)
Collecting certifi
  Using cached certifi-2020.11.8-py2.py3-none-any.whl (155 kB)
Building wheels for collected packages: pygrib
  Building wheel for pygrib (setup.py): started
  Building wheel for pygrib (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /tmp/ENV/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nvzp52bn/pygrib_992882a9deb54e16afb6d86b592edd71/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nvzp52bn/pygrib_992882a9deb54e16afb6d86b592edd71/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-m2hyiys9
       cwd: /tmp/pip-install-nvzp52bn/pygrib_992882a9deb54e16afb6d86b592edd71/
  Complete output (53 lines):
  reading from setup.cfg...running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  copying ncepgrib2.py -> build/lib.linux-x86_64-3.8
  running build_ext
  building 'redtoreg' extension
  creating build/temp.linux-x86_64-3.8
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/opt/include -fPIC -I/tmp/ENV/include -I/var/lang/include/python3.8 -I/tmp/pip-install-nvzp52bn/pygrib_992882a9deb54e16afb6d86b592edd71/.eggs/numpy-1.19.4-py3.8-linux-x86_64.egg/numpy/core/include -c redtoreg.c -o build/temp.linux-x86_64-3.8/redtoreg.o
  In file included from /tmp/pip-install-nvzp52bn/pygrib_992882a9deb54e16afb6d86b592edd71/.eggs/numpy-1.19.4-py3.8-linux-x86_64.egg/numpy/core/include/numpy/ndarraytypes.h:1822:0,
                   from /tmp/pip-install-nvzp52bn/pygrib_992882a9deb54e16afb6d86b592edd71/.eggs/numpy-1.19.4-py3.8-linux-x86_64.egg/numpy/core/include/numpy/ndarrayobject.h:12,
                   from /tmp/pip-install-nvzp52bn/pygrib_992882a9deb54e16afb6d86b592edd71/.eggs/numpy-1.19.4-py3.8-linux-x86_64.egg/numpy/core/include/numpy/arrayobject.h:4,
                   from redtoreg.c:606:
  /tmp/pip-install-nvzp52bn/pygrib_992882a9deb54e16afb6d86b592edd71/.eggs/numpy-1.19.4-py3.8-linux-x86_64.egg/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it with " \
    ^~~~~~~
  gcc -pthread -shared -Wl,-rpath=/var/lang/lib -L/opt/lib -I/opt/include build/temp.linux-x86_64-3.8/redtoreg.o -L/var/lang/lib -o build/lib.linux-x86_64-3.8/redtoreg.cpython-38-x86_64-linux-gnu.so
  building 'pygrib' extension
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/opt/include -fPIC -I/opt/local/include -I/opt/local/include -I/opt/local/include/jasper -I/opt/local/include -I/opt/local/include -I/opt/local/include -Ig2clib_src -I/tmp/ENV/include -I/var/lang/include/python3.8 -I/tmp/pip-install-nvzp52bn/pygrib_992882a9deb54e16afb6d86b592edd71/.eggs/numpy-1.19.4-py3.8-linux-x86_64.egg/numpy/core/include -c pygrib.c -o build/temp.linux-x86_64-3.8/pygrib.o
  In file included from /tmp/pip-install-nvzp52bn/pygrib_992882a9deb54e16afb6d86b592edd71/.eggs/numpy-1.19.4-py3.8-linux-x86_64.egg/numpy/core/include/numpy/ndarraytypes.h:1822:0,
                   from /tmp/pip-install-nvzp52bn/pygrib_992882a9deb54e16afb6d86b592edd71/.eggs/numpy-1.19.4-py3.8-linux-x86_64.egg/numpy/core/include/numpy/ndarrayobject.h:12,
                   from /tmp/pip-install-nvzp52bn/pygrib_992882a9deb54e16afb6d86b592edd71/.eggs/numpy-1.19.4-py3.8-linux-x86_64.egg/numpy/core/include/numpy/arrayobject.h:4,
                   from pygrib.c:606:
  /tmp/pip-install-nvzp52bn/pygrib_992882a9deb54e16afb6d86b592edd71/.eggs/numpy-1.19.4-py3.8-linux-x86_64.egg/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   #warning "Using deprecated NumPy API, disable it with " \
    ^~~~~~~
  pygrib.c: In function ‘__pyx_pf_6pygrib_11gribmessage_16keys’:
  pygrib.c:14153:18: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
       __pyx_v_name = grib_keys_iterator_get_name(__pyx_v_gi);
                    ^
  pygrib.c: In function ‘__pyx_pf_6pygrib_11gribmessage_18_read_only_keys’:
  pygrib.c:14587:18: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
       __pyx_v_name = grib_keys_iterator_get_name(__pyx_v_gi);
                    ^
  pygrib.c: In function ‘__pyx_pf_6pygrib_11gribmessage_30tostring’:
  pygrib.c:18740:53: warning: passing argument 2 of ‘grib_get_message’ from incompatible pointer type [-Wincompatible-pointer-types]
     __pyx_v_err = grib_get_message(__pyx_v_self->_gh, (&__pyx_v_message), (&__pyx_v_size));
                                                       ^
  In file included from pygrib.c:607:0:
  /opt/include/grib_api.h:577:5: note: expected ‘const void **’ but argument is of type ‘void **’
   int grib_get_message(const grib_handle* h, const void** message, size_t* message_length);
       ^~~~~~~~~~~~~~~~
  pygrib.c: In function ‘__pyx_pymod_exec_pygrib’:
  pygrib.c:36093:3: warning: return makes integer from pointer without a cast [-Wint-conversion]
     import_array();
     ^~~~~~~~~~~~
  gcc -pthread -shared -Wl,-rpath=/var/lang/lib -L/opt/lib -I/opt/include build/temp.linux-x86_64-3.8/pygrib.o -L/opt/local/lib -L/opt/local/lib64 -L/opt/local/lib -L/opt/local/lib64 -L/opt/local/lib -L/opt/local/lib64 -L/opt/local/lib -L/opt/local/lib64 -L/opt/local/lib -L/opt/local/lib64 -L/var/lang/lib -Wl,--enable-new-dtags,-R/opt/local/lib -Wl,--enable-new-dtags,-R/opt/local/lib64 -Wl,--enable-new-dtags,-R/opt/local/lib -Wl,--enable-new-dtags,-R/opt/local/lib64 -Wl,--enable-new-dtags,-R/opt/local/lib -Wl,--enable-new-dtags,-R/opt/local/lib64 -Wl,--enable-new-dtags,-R/opt/local/lib -Wl,--enable-new-dtags,-R/opt/local/lib64 -Wl,--enable-new-dtags,-R/opt/local/lib -Wl,--enable-new-dtags,-R/opt/local/lib64 -leccodes -ljasper -lopenjpeg -lpng -lz -o build/lib.linux-x86_64-3.8/pygrib.cpython-38-x86_64-linux-gnu.so
  /usr/bin/ld: cannot find -ljasper
  /usr/bin/ld: cannot find -lopenjpeg
  /usr/bin/ld: cannot find -lpng
  collect2: error: ld returned 1 exit status
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pygrib
  Running setup.py clean for pygrib
Failed to build pygrib
Installing collected packages: certifi, pyproj, numpy, pygrib
    Running setup.py install for pygrib: started
    Running setup.py install for pygrib: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /tmp/ENV/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nvzp52bn/pygrib_992882a9deb54e16afb6d86b592edd71/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nvzp52bn/pygrib_992882a9deb54e16afb6d86b592edd71/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-kn2kbzu6/install-record.txt --single-version-externally-managed --compile --install-headers /tmp/ENV/include/site/python3.8/pygrib
         cwd: /tmp/pip-install-nvzp52bn/pygrib_992882a9deb54e16afb6d86b592edd71/
    Complete output (78 lines):
    reading from setup.cfg...running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    copying ncepgrib2.py -> build/lib.linux-x86_64-3.8
    running build_ext
    building 'g2clib' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/g2clib_src
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/opt/include -fPIC -DUSE_JPEG2000=1 -DUSE_PNG=1 -D__64BIT__=1 -I/opt/local/include -I/opt/local/include -I/opt/local/include/jasper -I/opt/local/include -I/opt/local/include -I/opt/local/include -Ig2clib_src -I/tmp/ENV/include -I/var/lang/include/python3.8 -I/tmp/ENV/lib/python3.8/site-packages/numpy/core/include -c g2clib_src/g2_addlocal.c -o build/temp.linux-x86_64-3.8/g2clib_src/g2_addlocal.o
    g2clib_src/g2_addlocal.c: In function ‘g2_addlocal’:
    g2clib_src/g2_addlocal.c:105:63: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘g2int {aka int}’ [-Wformat=]
               printf("g2_addlocal: Sum of section byte counts = %ld\n",len);
                                                                 ~~^
                                                                 %d
    g2clib_src/g2_addlocal.c:106:66: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘g2int {aka int}’ [-Wformat=]
               printf("g2_addlocal: Total byte count in Section 0 = %ld\n",lencurr);
                                                                    ~~^
                                                                    %d
    g2clib_src/g2_addlocal.c:116:40: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘g2int {aka int}’ [-Wformat=]
             printf("g2_addlocal: Section %ld was the last found in given GRIB message.\n",isecnum);
                                          ~~^
                                          %d
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/opt/include -fPIC -DUSE_JPEG2000=1 -DUSE_PNG=1 -D__64BIT__=1 -I/opt/local/include -I/opt/local/include -I/opt/local/include/jasper -I/opt/local/include -I/opt/local/include -I/opt/local/include -Ig2clib_src -I/tmp/ENV/include -I/var/lang/include/python3.8 -I/tmp/ENV/lib/python3.8/site-packages/numpy/core/include -c g2clib_src/g2_unpack5.c -o build/temp.linux-x86_64-3.8/g2clib_src/g2_unpack5.o
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/opt/include -fPIC -DUSE_JPEG2000=1 -DUSE_PNG=1 -D__64BIT__=1 -I/opt/local/include -I/opt/local/include -I/opt/local/include/jasper -I/opt/local/include -I/opt/local/include -I/opt/local/include -Ig2clib_src -I/tmp/ENV/include -I/var/lang/include/python3.8 -I/tmp/ENV/lib/python3.8/site-packages/numpy/core/include -c g2clib_src/rdieee.c -o build/temp.linux-x86_64-3.8/g2clib_src/rdieee.o
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/opt/include -fPIC -DUSE_JPEG2000=1 -DUSE_PNG=1 -D__64BIT__=1 -I/opt/local/include -I/opt/local/include -I/opt/local/include/jasper -I/opt/local/include -I/opt/local/include -I/opt/local/include -Ig2clib_src -I/tmp/ENV/include -I/var/lang/include/python3.8 -I/tmp/ENV/lib/python3.8/site-packages/numpy/core/include -c g2clib_src/g2_unpack4.c -o build/temp.linux-x86_64-3.8/g2clib_src/g2_unpack4.o
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/opt/include -fPIC -DUSE_JPEG2000=1 -DUSE_PNG=1 -D__64BIT__=1 -I/opt/local/include -I/opt/local/include -I/opt/local/include/jasper -I/opt/local/include -I/opt/local/include -I/opt/local/include -Ig2clib_src -I/tmp/ENV/include -I/var/lang/include/python3.8 -I/tmp/ENV/lib/python3.8/site-packages/numpy/core/include -c g2clib_src/g2_free.c -o build/temp.linux-x86_64-3.8/g2clib_src/g2_free.o
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/opt/include -fPIC -DUSE_JPEG2000=1 -DUSE_PNG=1 -D__64BIT__=1 -I/opt/local/include -I/opt/local/include -I/opt/local/include/jasper -I/opt/local/include -I/opt/local/include -I/opt/local/include -Ig2clib_src -I/tmp/ENV/include -I/var/lang/include/python3.8 -I/tmp/ENV/lib/python3.8/site-packages/numpy/core/include -c g2clib_src/g2_addfield.c -o build/temp.linux-x86_64-3.8/g2clib_src/g2_addfield.o
    g2clib_src/g2_addfield.c: In function ‘g2_addfield’:
    g2clib_src/g2_addfield.c:193:63: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘g2int {aka int}’ [-Wformat=]
               printf("g2_addfield: Sum of section byte counts = %ld\n",len);
                                                                 ~~^
                                                                 %d
    g2clib_src/g2_addfield.c:194:66: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘g2int {aka int}’ [-Wformat=]
               printf("g2_addfield: Total byte count in Section 0 = %ld\n",lencurr);
                                                                    ~~^
                                                                    %d
    g2clib_src/g2_addfield.c:351:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                else if ( width==allones || height==allones ) {
                               ^~
    g2clib_src/g2_addfield.c:351:46: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                else if ( width==allones || height==allones ) {
                                                  ^~
    g2clib_src/g2_addfield.c:377:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                else if ( width==allones || height==allones ) {
                               ^~
    g2clib_src/g2_addfield.c:377:46: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                else if ( width==allones || height==allones ) {
                                                  ^~
    g2clib_src/g2_addfield.c:395:63: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘g2int {aka int}’ [-Wformat=]
             printf("g2_addfield: Data Representation Template 5.%ld not yet implemented.\n",idrsnum);
                                                                 ~~^
                                                                 %d
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/opt/include -fPIC -DUSE_JPEG2000=1 -DUSE_PNG=1 -D__64BIT__=1 -I/opt/local/include -I/opt/local/include -I/opt/local/include/jasper -I/opt/local/include -I/opt/local/include -I/opt/local/include -Ig2clib_src -I/tmp/ENV/include -I/var/lang/include/python3.8 -I/tmp/ENV/lib/python3.8/site-packages/numpy/core/include -c g2clib_src/g2_unpack3.c -o build/temp.linux-x86_64-3.8/g2clib_src/g2_unpack3.o
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/opt/include -fPIC -DUSE_JPEG2000=1 -DUSE_PNG=1 -D__64BIT__=1 -I/opt/local/include -I/opt/local/include -I/opt/local/include/jasper -I/opt/local/include -I/opt/local/include -I/opt/local/include -Ig2clib_src -I/tmp/ENV/include -I/var/lang/include/python3.8 -I/tmp/ENV/lib/python3.8/site-packages/numpy/core/include -c g2clib_src/misspack.c -o build/temp.linux-x86_64-3.8/g2clib_src/misspack.o
    g2clib_src/misspack.c: In function ‘misspack’:
    g2clib_src/misspack.c:74:46: warning: variable ‘ij’ set but not used [-Wunused-but-set-variable]
           g2int  nglenref, nglenlast, nbitsglen, ij;
                                                  ^~
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/opt/include -fPIC -DUSE_JPEG2000=1 -DUSE_PNG=1 -D__64BIT__=1 -I/opt/local/include -I/opt/local/include -I/opt/local/include/jasper -I/opt/local/include -I/opt/local/include -I/opt/local/include -Ig2clib_src -I/tmp/ENV/include -I/var/lang/include/python3.8 -I/tmp/ENV/lib/python3.8/site-packages/numpy/core/include -c g2clib_src/simunpack.c -o build/temp.linux-x86_64-3.8/g2clib_src/simunpack.o
    g2clib_src/simunpack.c: In function ‘simunpack’:
    g2clib_src/simunpack.c:42:22: warning: variable ‘itype’ set but not used [-Wunused-but-set-variable]
           g2int  j,nbits,itype;
                          ^~~~~
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/opt/include -fPIC -DUSE_JPEG2000=1 -DUSE_PNG=1 -D__64BIT__=1 -I/opt/local/include -I/opt/local/include -I/opt/local/include/jasper -I/opt/local/include -I/opt/local/include -I/opt/local/include -Ig2clib_src -I/tmp/ENV/include -I/var/lang/include/python3.8 -I/tmp/ENV/lib/python3.8/site-packages/numpy/core/include -c g2clib_src/seekgb.c -o build/temp.linux-x86_64-3.8/g2clib_src/seekgb.o
    g2clib_src/seekgb.c: In function ‘seekgb’:
    g2clib_src/seekgb.c:38:14: warning: variable ‘ret’ set but not used [-Wunused-but-set-variable]
           g2int  ret;
                  ^~~
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/opt/include -fPIC -DUSE_JPEG2000=1 -DUSE_PNG=1 -D__64BIT__=1 -I/opt/local/include -I/opt/local/include -I/opt/local/include/jasper -I/opt/local/include -I/opt/local/include -I/opt/local/include -Ig2clib_src -I/tmp/ENV/include -I/var/lang/include/python3.8 -I/tmp/ENV/lib/python3.8/site-packages/numpy/core/include -c g2clib_src/getpoly.c -o build/temp.linux-x86_64-3.8/g2clib_src/getpoly.o
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/opt/include -fPIC -DUSE_JPEG2000=1 -DUSE_PNG=1 -D__64BIT__=1 -I/opt/local/include -I/opt/local/include -I/opt/local/include/jasper -I/opt/local/include -I/opt/local/include -I/opt/local/include -Ig2clib_src -I/tmp/ENV/include -I/var/lang/include/python3.8 -I/tmp/ENV/lib/python3.8/site-packages/numpy/core/include -c g2clib_src/g2_unpack7.c -o build/temp.linux-x86_64-3.8/g2clib_src/g2_unpack7.o
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/opt/include -fPIC -DUSE_JPEG2000=1 -DUSE_PNG=1 -D__64BIT__=1 -I/opt/local/include -I/opt/local/include -I/opt/local/include/jasper -I/opt/local/include -I/opt/local/include -I/opt/local/include -Ig2clib_src -I/tmp/ENV/include -I/var/lang/include/python3.8 -I/tmp/ENV/lib/python3.8/site-packages/numpy/core/include -c g2clib_src/dec_png.c -o build/temp.linux-x86_64-3.8/g2clib_src/dec_png.o
    g2clib_src/dec_png.c:8:10: fatal error: png.h: No such file or directory
     #include <png.h>
              ^~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /tmp/ENV/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nvzp52bn/pygrib_992882a9deb54e16afb6d86b592edd71/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nvzp52bn/pygrib_992882a9deb54e16afb6d86b592edd71/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-kn2kbzu6/install-record.txt --single-version-externally-managed --compile --install-headers /tmp/ENV/include/site/python3.8/pygrib Check the logs for full command output.
```
</details>

The same setup work fine with `pygrib==2.0.4`:
<details>
  <summary>Click to see logs</summary>

```
$ pip install --upgrade pyproj numpy
Collecting numpy
  Using cached numpy-1.19.4-cp38-cp38-manylinux2010_x86_64.whl (14.5 MB)
Collecting pyproj
  Using cached pyproj-3.0.0.post1-cp38-cp38-manylinux2010_x86_64.whl (6.5 MB)
Collecting certifi
  Using cached certifi-2020.11.8-py2.py3-none-any.whl (155 kB)
Installing collected packages: certifi, pyproj, numpy
Successfully installed certifi-2020.11.8 numpy-1.19.4 pyproj-3.0.0.post1

$ pip install --upgrade pygrib==2.0.4
Collecting pygrib==2.0.4
  Using cached pygrib-2.0.4-cp38-cp38-linux_x86_64.whl
Requirement already satisfied: numpy in /tmp/ENV/lib/python3.8/site-packages (from pygrib==2.0.4) (1.19.4)
Installing collected packages: pygrib
Successfully installed pygrib-2.0.4
```
</details>

Libs requirements are changed between versions?

**Comment by jswhit** [comment]
Looks like the jasper, png and/or openjpeg headers and libs are not being found.  Can you try installing 2.1?  The build script (setup.py) has been updated to search a few standard locations.

**Comment by jswhit** [comment]
setting LDFLAGS and CPPFLAGS may help also

**Comment by fox91** [comment]
Problem confirmed with `pygrib==2.0.6`.
Solved with `pygrib==2.1`.

Thanks
